name: SymfonyFastTrackTutorial
recipe: lamp

config:
  webroot: public
  xdebug: true
  php: '8.0'
  database: 'mariadb'

services:
  appserver:
    build:
      - echo "Installing Symfony CLI"
      - wget https://get.symfony.com/cli/installer -O - | bash
      - echo "Move Symfony binary"
      - mv /var/www/.symfony/bin/symfony /usr/local/bin/symfony
  database:
    portforward: 3306
  node:
    type: node:14

tooling:
  symfony:
    service: appserver
  console:
    service: appserver
    cmd: php bin/console
  npm:
    service: node